pip install --no-index --find-links C:\Users\nox\Desktop\wheel2 beautifulsoup4-4.11.1-py3-none-any.whl
pip install --no-index --find-links C:\Users\nox\Desktop\wheel2 Flask-2.2.2-py3-none-any.whl
pip install --no-index --find-links C:\Users\nox\Desktop\wheel2 google_api_python_client-1.8.0-py3-none-any.whl
pip install --no-index --find-links C:\Users\nox\Desktop\wheel2 google_api_python_client-2.65.0-py2.py3-none-any.whl
pip install --no-index --find-links C:\Users\nox\Desktop\wheel2 instaloader-4.9.5.tar.gz
pip install --no-index --find-links C:\Users\nox\Desktop\wheel2 IPTCInfo3-2.1.4-py3-none-any.whl
pip install --no-index --find-links C:\Users\nox\Desktop\wheel2 lxml-4.9.0-cp311-cp311-win_amd64.whl
pip install --no-index --find-links C:\Users\nox\Desktop\wheel2 Markdown-3.4.1-py3-none-any.whl
pip install --no-index --find-links C:\Users\nox\Desktop\wheel2 matplotlib-3.6.0-cp311-cp311-win_amd64.whl
pip install --no-index --find-links C:\Users\nox\Desktop\wheel2 mutagen-1.45.1-py3-none-any.whl
pip install --no-index --find-links C:\Users\nox\Desktop\wheel2 Pillow-9.2.0-cp311-cp311-win_amd64.whl
pip install --no-index --find-links C:\Users\nox\Desktop\wheel2 Pygments-2.13.0-py3-none-any.whl
pip install --no-index --find-links C:\Users\nox\Desktop\wheel2 pyinstaller-4.5.1-py3-none-win_amd64.whl
pip install --no-index --find-links C:\Users\nox\Desktop\wheel2 PyMySQL-1.0.2-py3-none-any.whl
pip install --no-index --find-links C:\Users\nox\Desktop\wheel2 pywin32-304-cp311-cp311-win_amd64.whl
pip install --no-index --find-links C:\Users\nox\Desktop\wheel2 rawpy-0.17.3-cp310-cp310-win_amd64.whl
pip install --no-index --find-links C:\Users\nox\Desktop\wheel2 requests-2.28.1-py3-none-any.whl
pip install --no-index --find-links C:\Users\nox\Desktop\wheel2 tqdm-4.64.1-py2.py3-none-any.whl
pip install --no-index --find-links C:\Users\nox\Desktop\wheel2 yt_dlp-2022.10.4-py2.py3-none-any.whl
